# Operating Systems
"os: windows":
  - "[X] Windows"

"os: mac":
  - "[X] MacOS"

"os: linux":
  - "[X] Linux"

"os: indiscriminate":
  - "[X] Indiscriminate"

# Projects
"project: holocure.api":
 - "[X] HoloCure.API"

"project: holocure.modloader.api":
 - "[X] HoloCure.ModLoader.API"

"project: holocure.modloader.logging":
 - "[X] HoloCure.ModLoader.Logging"

"project: holocure.modloader.updater":
 - "[X] HoloCure.ModLoader.Updater"

"project: holocure.modloader":
 - "[X] HoloCure.ModLoader"

"project: codechicken.diffpatch":
 - "[X] CodeChicken.DiffPath"

"project: undertalemodlib":
 - "[X] UndertaleModLib"
